### ISSUE TITLE
Raspberry Pi installer `chown` error

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/device-agent#192] opened 2023-11-04 20:45 UTC
### Current Behavior

Found in the logs:

```
chown: missing operand after ‘/opt/flowforge-device’
```

It appears `$SUDO_USER` has not been defined, and the command that runs is basically `chown -R /opt/flowforge-device`.
This I've validated by `cat`ing the service file.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment] 2023-11-04 20:46
Dupe of https://github.com/FlowFuse/device-agent/issues/187

**Closed** 2023-11-04 20:59 UTC
Labels: needs-triage
